### ISSUE TITLE
Spike: Understand Postgresql Table Partitioning

### ISSUE THREAD

**Issue by EvanParish** [department-of-veterans-affairs/va-enp-api#64]
## User Story - Business Goal

We want to use table partitioning to ensure our database remains performant as we continue to grow as a platform.

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** backend engineer 
**I want** understand how we can implement partitioning 
**So that** we can make our postgresql db as performant as possible  

### Additional Info and Resources

- Postgres [Table Partitioning](https://www.postgresql.org/docs/current/ddl-partitioning.html)
## Acceptance Criteria & Checklist

- [x] Table partitioning has been added to the ENP database for the relevant tables (notification), or a new ticket is created for implementation, if it's not simple once we understand how it's done.
- [x] Tickets for next steps have been identified and created
- [ ] Technical Documentation has been created and linked in the glossary
- [ ] Learnings have been shared with the team, and decisions have been documented

Completed research addresses the problems and/or answers the questions below:  

1. How can we implement partitioning for our relevant tables for VA ENP?
2. What type of partitioning is appropriate for our use-case? (most likely range, but please confirm)

**Comment by MackHalliday** [comment]
- Discussion with @EvanParish. Recommended on partitioning by year (date-based), may look into other attributes. Should try to implement in ENP if not too complex
- Need to understand how easily partitioning can be modified in the future (e.g., switching to shorter date ranges).
- Would like to  test queries across multiple partitions to evaluate performance and partition pruning.

**Comment by MackHalliday** [comment]
Friday 
- Talked to Evan 
- Read doc provided in ticket and listen to [podcast on Partitioning ](https://postgres.fm/episodes/partitioning)
- Tried implementing Partitioning 

Today 
- Will create ticket, difficult to test Partitioning without test database
- Figure out size of current DB

**Comment by MackHalliday** [comment]
Rollover 
- Would like to spend some more time looking a queries in DataDog and explore automatic script for partitioning Notification table. 
-

**Comment by MackHalliday** [comment]
Closing ticket 
- Discussed implementation with @k-macmillan. He is OK with implementing partition based on year.
- Discussed adding event listener to automatically create new year-based tables as needed and implementing with NotificationMixIn
- Created Spike doc 
- [Updated new ticket based on discussion with ](https://github.com/orgs/department-of-veterans-affairs/projects/1417/views/1?pane=issue&itemId=90319716&issue=department-of-veterans-affairs%7Cva-enp-api%7C95)@k-macmillan
