### ISSUE TITLE
Custom FastAPI and ENPState Classes

### ISSUE THREAD

**Issue by EvanParish** [department-of-veterans-affairs/va-enp-api#78]
## User Story - Business Need

We have been having trouble using the app state in testing because it's not strongly typed and mypy takes issue with that. This has caused some inefficiencies in the code so far. Creating a custom ENPState class with the required attributes and adding it to a FastAPI subclass should fix this issues.

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** backend engineer   
**I want** to create custom classes   
**So that** we can have static type checking and appease the mypy gods  

### Additional Info and Resources

- The app state is currently used to hold the AWS provider and is accessed in the routes that have been implemented so far.
- Ensure this newly implemented class will work in testing scenarios by running the `scripts/run_checks.sh` script

## Acceptance Criteria

- [x] An `ENPState` class exists and has the `providers` attribute 
    - Name the class something that makes sense, it doesn't have to be "ENPState"
- [x] A custom FastAPI subclass exists and includes the created State attribute
- [x] Everywhere the app state was being used has been updated appropriately (code and tests)
    - [ ] ~~the presence of `# type: ignore` related to app state is removed~~ Unable to resolved. OK-ed removing requirements with @k-macmillan 
- [x] Routes using the Provider use the instance from state, not new instances.
- [x] Mypy can determine that a request has a state object, with providers, and the type of provider.
- [x] This work is added to the sprint review slide deck (key win bullet point and demo slide)

**Comment by MackHalliday** [comment]
Yesterday 
- Start writing basic testing 
- Create Custom FastAPI and ENPState Class

**Comment by MackHalliday** [comment]
Yesterday 
- Fix issues with docstring and typing 
- Add additional testing to reach 100% test coverage

Today 
- OOO until tomorrow. When I'm back I'll be focusing on the test coverage. Currently getting error "FAIL Required test coverage of 100.0% not reached. Total coverage: 99.10%". Not sure what needs to be tested to reach 100%

**Comment by MackHalliday** [comment]
Today 
- Added a few more tests
- Still getting the same error we were trying to solve for. 
- Planning on meeting with @EvanParish at 8 AM CST tomorrow to figure out a better fix.

**Comment by MackHalliday** [comment]
Today 
- Meet with @EvanParish this morning, could not find work around 
- Send message to @k-macmillan noting the state of the ticket and how to proceed.

**Comment by MackHalliday** [comment]
Today 
- Talked with @k-macmillan and he helped with me a solution to get pass the "no enp_state" MyPy error 
- Implemented his solution 
- Getting a new MyPy error related to mocking `"Callable[[DeviceRegistrationModel], Coroutine[Any, Any, str]]" has no attribute "return_value` -> Anticipating fix being easy. 
- Still need to swap out all the TestClients for ENPTestClient 
- Need to figure out what Type Provider should be in ENPState class - currently ProviderAWS.
